### ISSUE TITLE
Crash when switching to Front Camera

### ISSUE THREAD

**Issue by aftabsikander** [flurgle/CameraKit-Android#5]
Play store Application is getting crashed when switching Front Face Camera from option

# Device Information
```
Brand: Google
DeviceModel: Nexus 5
Product: hammerhead
Manufacturer: LGE
Android Version: 6.0.1
```

**Crash Logs**

```
FATAL EXCEPTION: main
Process: com.flurgle.camerakit.demo, PID: 10110 java.util.NoSuchElementException
at java.util.TreeMap.lastKey(TreeMap.java:630)
at java.util.TreeSet.last(TreeSet.java:272)
at com.flurgle.camerakit.Camera1.getPreviewResolution(Camera1.java:261)
at com.flurgle.camerakit.Camera1.adjustCameraParameters(Camera1.java:333)
at com.flurgle.camerakit.Camera1.openCamera(Camera1.java:292)
at com.flurgle.camerakit.Camera1.start(Camera1.java:74)
at com.flurgle.camerakit.Camera1.setFacing(Camera1.java:108)
at com.flurgle.camerakit.CameraView.setFacing(CameraView.java:163)
at com.flurgle.camerakit.CameraView.toggleFacing(CameraView.java:198)
at com.flurgle.camerakit.demo.MainActivity.toggleCamera(MainActivity.java:148)
at com.flurgle.camerakit.demo.MainActivity_ViewBinding$5.doClick(MainActivity_ViewBinding.java:88)
at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
at android.view.View.performClick(View.java:5204)
at android.view.View$PerformClick.run(View.java:21153)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**How to reproduce this issue.**

- Download Application From Google Play Store

- Open Application give permissions and switch camera to **Front Face**, As soon as you click button application is crashed

**Comment by baurine** [comment]
@aftabsikander it's true, it also crashed in my phone, try the latest code in the master branch, that's ok on my phone. this bug should be fixed in the commit: [fix flipping camera](https://github.com/flurgle/CameraKit-Android/commit/0a2a94245c31b628da7c1b1d9153b8db497e0e12)

**Comment by sohayb** [comment]
@aftabsikander did the issue get resolved as @baurine stated? if yes, can you please close the issue?

**Comment by aftabsikander** [comment]
@sohayb I would test this by day end, Will close this once I check it out

**Comment by dwillmc** [comment]
An update was just pushed which should rollout in the next few hours and fix this problem.
Please re-open if you get the update and it still doesn't work!
